import type { ToolResult } from "@/lib/health-tools.server";

const BRAND = "Generated by Nirogi AI — nirogi-healthai.lovable.app";
const DISCLAIMER = "AI-generated for awareness only. Consult a doctor.";

function fmtDate(d: Date) {
  return d.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
}

export type ReportSource = {
  toolName: string;
  /** Structured AI result (most tools). */
  result?: ToolResult | null;
  /** Plain-text analysis (e.g. prescription reading). */
  text?: string | null;
  date?: Date;
};

/** Build a clean, shareable plain-text report. */
export function formatReport(src: ReportSource): string {
  const date = src.date ?? new Date();
  const lines: string[] = [];
  lines.push(`*${src.toolName}* — ${fmtDate(date)}`);
  lines.push("");

  const r = src.result;
  if (r) {
    if (r.title) lines.push(r.title);
    const flags: string[] = [];
    if (r.riskLevel) flags.push(`Risk: ${r.riskLevel.toUpperCase()}`);
    if (r.urgency) flags.push(`Urgency: ${r.urgency.toUpperCase()}`);
    if (flags.length) lines.push(flags.join("  |  "));
    if (r.summary) {
      lines.push("");
      lines.push(r.summary);
    }
    if (typeof r.preventionScore === "number") {
      lines.push("");
      lines.push(`Prevention Score: ${r.preventionScore}/100`);
    }
    if (r.sugarImpact?.score != null) {
      lines.push("");
      lines.push(
        `Sugar Impact Index: ${r.sugarImpact.score}/100${r.sugarImpact.verdict ? ` (${r.sugarImpact.verdict})` : ""}`,
      );
    }
    if (r.nutrition) {
      const n = r.nutrition;
      lines.push("");
      lines.push(
        `Nutrition: ${n.calories ?? "?"} kcal, ${n.protein_g ?? "?"}g protein, ${n.sugar_g ?? "?"}g sugar, ${n.sodium_mg ?? "?"}mg sodium`,
      );
    }
    for (const s of r.sections ?? []) {
      lines.push("");
      lines.push(`${s.heading}:`);
      for (const item of s.items) lines.push(`• ${item}`);
    }
    if (r.warnings?.length) {
      lines.push("");
      lines.push("Warnings:");
      for (const w of r.warnings) lines.push(`! ${w}`);
    }
    if (r.recommendations?.length) {
      lines.push("");
      lines.push("Recommendations:");
      for (const rec of r.recommendations) lines.push(`✓ ${rec}`);
    }
    if (r.specialist) {
      lines.push("");
      lines.push(`Consider seeing: ${r.specialist}`);
    }
  } else if (src.text) {
    lines.push(src.text.trim());
  }

  lines.push("");
  lines.push("—");
  lines.push(BRAND);
  lines.push(DISCLAIMER);
  return lines.join("\n");
}

/** Build a WhatsApp share URL pre-filled with the report text. */
export function whatsappShareUrl(src: ReportSource): string {
  const text = formatReport(src).replace(/\*/g, ""); // strip markdown emphasis for clean text
  return `https://wa.me/?text=${encodeURIComponent(text)}`;
}

/** Generate and download a branded PDF of the report (client-only). */
export async function downloadReportPdf(src: ReportSource): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const ensureSpace = (h: number) => {
    if (y + h > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Header band
  doc.setFillColor(13, 110, 124);
  doc.rect(0, 0, pageWidth, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Nirogi AI", margin, 44);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(src.toolName, pageWidth - margin, 44, { align: "right" });
  y = 100;

  doc.setTextColor(30, 30, 30);

  const text = formatReport(src)
    .replace(/\*/g, "")
    .replace(/^—$/m, "____________________________________________");

  const blocks = text.split("\n");
  for (const block of blocks) {
    if (block.trim() === "") {
      y += 8;
      continue;
    }
    const isHeading = /:$/.test(block) && block.length < 60;
    doc.setFont("helvetica", isHeading ? "bold" : "normal");
    doc.setFontSize(isHeading ? 12 : 10.5);
    const wrapped = doc.splitTextToSize(block, maxWidth) as string[];
    for (const line of wrapped) {
      ensureSpace(16);
      doc.text(line, margin, y);
      y += 15;
    }
  }

  const safeName = src.toolName.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  doc.save(`nirogi-${safeName}-report.pdf`);
}
