/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SosRouteImport } from './routes/sos'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedWaterTrackerRouteImport } from './routes/_authenticated/water-tracker'
import { Route as AuthenticatedSleepTrackerRouteImport } from './routes/_authenticated/sleep-tracker'
import { Route as AuthenticatedSenseCheckRouteImport } from './routes/_authenticated/sense-check'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedHeartRhythmRouteImport } from './routes/_authenticated/heart-rhythm'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedExerciseTrackerRouteImport } from './routes/_authenticated/exercise-tracker'
import { Route as AuthenticatedDietPlanRouteImport } from './routes/_authenticated/diet-plan'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBreatheRouteImport } from './routes/_authenticated/breathe'
import { Route as AuthenticatedToolsToolRouteImport } from './routes/_authenticated/tools/$tool'
import { Route as AuthenticatedDashboardWeightRouteImport } from './routes/_authenticated/dashboard.weight'
import { Route as AuthenticatedDashboardUvRouteImport } from './routes/_authenticated/dashboard.uv'
import { Route as AuthenticatedDashboardTemperatureRouteImport } from './routes/_authenticated/dashboard.temperature'
import { Route as AuthenticatedDashboardStressRouteImport } from './routes/_authenticated/dashboard.stress'
import { Route as AuthenticatedDashboardOxygenRouteImport } from './routes/_authenticated/dashboard.oxygen'
import { Route as AuthenticatedDashboardHearingRouteImport } from './routes/_authenticated/dashboard.hearing'
import { Route as AuthenticatedDashboardGlucoseRouteImport } from './routes/_authenticated/dashboard.glucose'
import { Route as AuthenticatedDashboardEyeStrainRouteImport } from './routes/_authenticated/dashboard.eye-strain'
import { Route as AuthenticatedDashboardEnergyRouteImport } from './routes/_authenticated/dashboard.energy'
import { Route as AuthenticatedDashboardDevicesRouteImport } from './routes/_authenticated/dashboard.devices'
import { Route as AuthenticatedDashboardBoneHealthRouteImport } from './routes/_authenticated/dashboard.bone-health'
import { Route as AuthenticatedDashboardBioAgeRouteImport } from './routes/_authenticated/dashboard.bio-age'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWaterTrackerRoute =
  AuthenticatedWaterTrackerRouteImport.update({
    id: '/water-tracker',
    path: '/water-tracker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSleepTrackerRoute =
  AuthenticatedSleepTrackerRouteImport.update({
    id: '/sleep-tracker',
    path: '/sleep-tracker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSenseCheckRoute = AuthenticatedSenseCheckRouteImport.update({
  id: '/sense-check',
  path: '/sense-check',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHeartRhythmRoute =
  AuthenticatedHeartRhythmRouteImport.update({
    id: '/heart-rhythm',
    path: '/heart-rhythm',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExerciseTrackerRoute =
  AuthenticatedExerciseTrackerRouteImport.update({
    id: '/exercise-tracker',
    path: '/exercise-tracker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDietPlanRoute = AuthenticatedDietPlanRouteImport.update({
  id: '/diet-plan',
  path: '/diet-plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBreatheRoute = AuthenticatedBreatheRouteImport.update({
  id: '/breathe',
  path: '/breathe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsToolRoute = AuthenticatedToolsToolRouteImport.update({
  id: '/tools/$tool',
  path: '/tools/$tool',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardWeightRoute =
  AuthenticatedDashboardWeightRouteImport.update({
    id: '/weight',
    path: '/weight',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUvRoute =
  AuthenticatedDashboardUvRouteImport.update({
    id: '/uv',
    path: '/uv',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTemperatureRoute =
  AuthenticatedDashboardTemperatureRouteImport.update({
    id: '/temperature',
    path: '/temperature',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStressRoute =
  AuthenticatedDashboardStressRouteImport.update({
    id: '/stress',
    path: '/stress',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOxygenRoute =
  AuthenticatedDashboardOxygenRouteImport.update({
    id: '/oxygen',
    path: '/oxygen',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardHearingRoute =
  AuthenticatedDashboardHearingRouteImport.update({
    id: '/hearing',
    path: '/hearing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGlucoseRoute =
  AuthenticatedDashboardGlucoseRouteImport.update({
    id: '/glucose',
    path: '/glucose',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEyeStrainRoute =
  AuthenticatedDashboardEyeStrainRouteImport.update({
    id: '/eye-strain',
    path: '/eye-strain',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEnergyRoute =
  AuthenticatedDashboardEnergyRouteImport.update({
    id: '/energy',
    path: '/energy',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDevicesRoute =
  AuthenticatedDashboardDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBoneHealthRoute =
  AuthenticatedDashboardBoneHealthRouteImport.update({
    id: '/bone-health',
    path: '/bone-health',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBioAgeRoute =
  AuthenticatedDashboardBioAgeRouteImport.update({
    id: '/bio-age',
    path: '/bio-age',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/breathe': typeof AuthenticatedBreatheRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/diet-plan': typeof AuthenticatedDietPlanRoute
  '/exercise-tracker': typeof AuthenticatedExerciseTrackerRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/heart-rhythm': typeof AuthenticatedHeartRhythmRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/sense-check': typeof AuthenticatedSenseCheckRoute
  '/sleep-tracker': typeof AuthenticatedSleepTrackerRoute
  '/water-tracker': typeof AuthenticatedWaterTrackerRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/bio-age': typeof AuthenticatedDashboardBioAgeRoute
  '/dashboard/bone-health': typeof AuthenticatedDashboardBoneHealthRoute
  '/dashboard/devices': typeof AuthenticatedDashboardDevicesRoute
  '/dashboard/energy': typeof AuthenticatedDashboardEnergyRoute
  '/dashboard/eye-strain': typeof AuthenticatedDashboardEyeStrainRoute
  '/dashboard/glucose': typeof AuthenticatedDashboardGlucoseRoute
  '/dashboard/hearing': typeof AuthenticatedDashboardHearingRoute
  '/dashboard/oxygen': typeof AuthenticatedDashboardOxygenRoute
  '/dashboard/stress': typeof AuthenticatedDashboardStressRoute
  '/dashboard/temperature': typeof AuthenticatedDashboardTemperatureRoute
  '/dashboard/uv': typeof AuthenticatedDashboardUvRoute
  '/dashboard/weight': typeof AuthenticatedDashboardWeightRoute
  '/tools/$tool': typeof AuthenticatedToolsToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/breathe': typeof AuthenticatedBreatheRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/diet-plan': typeof AuthenticatedDietPlanRoute
  '/exercise-tracker': typeof AuthenticatedExerciseTrackerRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/heart-rhythm': typeof AuthenticatedHeartRhythmRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/sense-check': typeof AuthenticatedSenseCheckRoute
  '/sleep-tracker': typeof AuthenticatedSleepTrackerRoute
  '/water-tracker': typeof AuthenticatedWaterTrackerRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/bio-age': typeof AuthenticatedDashboardBioAgeRoute
  '/dashboard/bone-health': typeof AuthenticatedDashboardBoneHealthRoute
  '/dashboard/devices': typeof AuthenticatedDashboardDevicesRoute
  '/dashboard/energy': typeof AuthenticatedDashboardEnergyRoute
  '/dashboard/eye-strain': typeof AuthenticatedDashboardEyeStrainRoute
  '/dashboard/glucose': typeof AuthenticatedDashboardGlucoseRoute
  '/dashboard/hearing': typeof AuthenticatedDashboardHearingRoute
  '/dashboard/oxygen': typeof AuthenticatedDashboardOxygenRoute
  '/dashboard/stress': typeof AuthenticatedDashboardStressRoute
  '/dashboard/temperature': typeof AuthenticatedDashboardTemperatureRoute
  '/dashboard/uv': typeof AuthenticatedDashboardUvRoute
  '/dashboard/weight': typeof AuthenticatedDashboardWeightRoute
  '/tools/$tool': typeof AuthenticatedToolsToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/_authenticated/breathe': typeof AuthenticatedBreatheRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/diet-plan': typeof AuthenticatedDietPlanRoute
  '/_authenticated/exercise-tracker': typeof AuthenticatedExerciseTrackerRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/heart-rhythm': typeof AuthenticatedHeartRhythmRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/sense-check': typeof AuthenticatedSenseCheckRoute
  '/_authenticated/sleep-tracker': typeof AuthenticatedSleepTrackerRoute
  '/_authenticated/water-tracker': typeof AuthenticatedWaterTrackerRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/dashboard/bio-age': typeof AuthenticatedDashboardBioAgeRoute
  '/_authenticated/dashboard/bone-health': typeof AuthenticatedDashboardBoneHealthRoute
  '/_authenticated/dashboard/devices': typeof AuthenticatedDashboardDevicesRoute
  '/_authenticated/dashboard/energy': typeof AuthenticatedDashboardEnergyRoute
  '/_authenticated/dashboard/eye-strain': typeof AuthenticatedDashboardEyeStrainRoute
  '/_authenticated/dashboard/glucose': typeof AuthenticatedDashboardGlucoseRoute
  '/_authenticated/dashboard/hearing': typeof AuthenticatedDashboardHearingRoute
  '/_authenticated/dashboard/oxygen': typeof AuthenticatedDashboardOxygenRoute
  '/_authenticated/dashboard/stress': typeof AuthenticatedDashboardStressRoute
  '/_authenticated/dashboard/temperature': typeof AuthenticatedDashboardTemperatureRoute
  '/_authenticated/dashboard/uv': typeof AuthenticatedDashboardUvRoute
  '/_authenticated/dashboard/weight': typeof AuthenticatedDashboardWeightRoute
  '/_authenticated/tools/$tool': typeof AuthenticatedToolsToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cookies'
    | '/privacy'
    | '/sos'
    | '/terms'
    | '/breathe'
    | '/dashboard'
    | '/diet-plan'
    | '/exercise-tracker'
    | '/goals'
    | '/heart-rhythm'
    | '/history'
    | '/sense-check'
    | '/sleep-tracker'
    | '/water-tracker'
    | '/invite/$token'
    | '/dashboard/bio-age'
    | '/dashboard/bone-health'
    | '/dashboard/devices'
    | '/dashboard/energy'
    | '/dashboard/eye-strain'
    | '/dashboard/glucose'
    | '/dashboard/hearing'
    | '/dashboard/oxygen'
    | '/dashboard/stress'
    | '/dashboard/temperature'
    | '/dashboard/uv'
    | '/dashboard/weight'
    | '/tools/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cookies'
    | '/privacy'
    | '/sos'
    | '/terms'
    | '/breathe'
    | '/dashboard'
    | '/diet-plan'
    | '/exercise-tracker'
    | '/goals'
    | '/heart-rhythm'
    | '/history'
    | '/sense-check'
    | '/sleep-tracker'
    | '/water-tracker'
    | '/invite/$token'
    | '/dashboard/bio-age'
    | '/dashboard/bone-health'
    | '/dashboard/devices'
    | '/dashboard/energy'
    | '/dashboard/eye-strain'
    | '/dashboard/glucose'
    | '/dashboard/hearing'
    | '/dashboard/oxygen'
    | '/dashboard/stress'
    | '/dashboard/temperature'
    | '/dashboard/uv'
    | '/dashboard/weight'
    | '/tools/$tool'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cookies'
    | '/privacy'
    | '/sos'
    | '/terms'
    | '/_authenticated/breathe'
    | '/_authenticated/dashboard'
    | '/_authenticated/diet-plan'
    | '/_authenticated/exercise-tracker'
    | '/_authenticated/goals'
    | '/_authenticated/heart-rhythm'
    | '/_authenticated/history'
    | '/_authenticated/sense-check'
    | '/_authenticated/sleep-tracker'
    | '/_authenticated/water-tracker'
    | '/invite/$token'
    | '/_authenticated/dashboard/bio-age'
    | '/_authenticated/dashboard/bone-health'
    | '/_authenticated/dashboard/devices'
    | '/_authenticated/dashboard/energy'
    | '/_authenticated/dashboard/eye-strain'
    | '/_authenticated/dashboard/glucose'
    | '/_authenticated/dashboard/hearing'
    | '/_authenticated/dashboard/oxygen'
    | '/_authenticated/dashboard/stress'
    | '/_authenticated/dashboard/temperature'
    | '/_authenticated/dashboard/uv'
    | '/_authenticated/dashboard/weight'
    | '/_authenticated/tools/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  SosRoute: typeof SosRoute
  TermsRoute: typeof TermsRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/water-tracker': {
      id: '/_authenticated/water-tracker'
      path: '/water-tracker'
      fullPath: '/water-tracker'
      preLoaderRoute: typeof AuthenticatedWaterTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sleep-tracker': {
      id: '/_authenticated/sleep-tracker'
      path: '/sleep-tracker'
      fullPath: '/sleep-tracker'
      preLoaderRoute: typeof AuthenticatedSleepTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sense-check': {
      id: '/_authenticated/sense-check'
      path: '/sense-check'
      fullPath: '/sense-check'
      preLoaderRoute: typeof AuthenticatedSenseCheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/heart-rhythm': {
      id: '/_authenticated/heart-rhythm'
      path: '/heart-rhythm'
      fullPath: '/heart-rhythm'
      preLoaderRoute: typeof AuthenticatedHeartRhythmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exercise-tracker': {
      id: '/_authenticated/exercise-tracker'
      path: '/exercise-tracker'
      fullPath: '/exercise-tracker'
      preLoaderRoute: typeof AuthenticatedExerciseTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diet-plan': {
      id: '/_authenticated/diet-plan'
      path: '/diet-plan'
      fullPath: '/diet-plan'
      preLoaderRoute: typeof AuthenticatedDietPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/breathe': {
      id: '/_authenticated/breathe'
      path: '/breathe'
      fullPath: '/breathe'
      preLoaderRoute: typeof AuthenticatedBreatheRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/$tool': {
      id: '/_authenticated/tools/$tool'
      path: '/tools/$tool'
      fullPath: '/tools/$tool'
      preLoaderRoute: typeof AuthenticatedToolsToolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/weight': {
      id: '/_authenticated/dashboard/weight'
      path: '/weight'
      fullPath: '/dashboard/weight'
      preLoaderRoute: typeof AuthenticatedDashboardWeightRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/uv': {
      id: '/_authenticated/dashboard/uv'
      path: '/uv'
      fullPath: '/dashboard/uv'
      preLoaderRoute: typeof AuthenticatedDashboardUvRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/temperature': {
      id: '/_authenticated/dashboard/temperature'
      path: '/temperature'
      fullPath: '/dashboard/temperature'
      preLoaderRoute: typeof AuthenticatedDashboardTemperatureRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/stress': {
      id: '/_authenticated/dashboard/stress'
      path: '/stress'
      fullPath: '/dashboard/stress'
      preLoaderRoute: typeof AuthenticatedDashboardStressRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/oxygen': {
      id: '/_authenticated/dashboard/oxygen'
      path: '/oxygen'
      fullPath: '/dashboard/oxygen'
      preLoaderRoute: typeof AuthenticatedDashboardOxygenRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/hearing': {
      id: '/_authenticated/dashboard/hearing'
      path: '/hearing'
      fullPath: '/dashboard/hearing'
      preLoaderRoute: typeof AuthenticatedDashboardHearingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/glucose': {
      id: '/_authenticated/dashboard/glucose'
      path: '/glucose'
      fullPath: '/dashboard/glucose'
      preLoaderRoute: typeof AuthenticatedDashboardGlucoseRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/eye-strain': {
      id: '/_authenticated/dashboard/eye-strain'
      path: '/eye-strain'
      fullPath: '/dashboard/eye-strain'
      preLoaderRoute: typeof AuthenticatedDashboardEyeStrainRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/energy': {
      id: '/_authenticated/dashboard/energy'
      path: '/energy'
      fullPath: '/dashboard/energy'
      preLoaderRoute: typeof AuthenticatedDashboardEnergyRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/devices': {
      id: '/_authenticated/dashboard/devices'
      path: '/devices'
      fullPath: '/dashboard/devices'
      preLoaderRoute: typeof AuthenticatedDashboardDevicesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bone-health': {
      id: '/_authenticated/dashboard/bone-health'
      path: '/bone-health'
      fullPath: '/dashboard/bone-health'
      preLoaderRoute: typeof AuthenticatedDashboardBoneHealthRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bio-age': {
      id: '/_authenticated/dashboard/bio-age'
      path: '/bio-age'
      fullPath: '/dashboard/bio-age'
      preLoaderRoute: typeof AuthenticatedDashboardBioAgeRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBioAgeRoute: typeof AuthenticatedDashboardBioAgeRoute
  AuthenticatedDashboardBoneHealthRoute: typeof AuthenticatedDashboardBoneHealthRoute
  AuthenticatedDashboardDevicesRoute: typeof AuthenticatedDashboardDevicesRoute
  AuthenticatedDashboardEnergyRoute: typeof AuthenticatedDashboardEnergyRoute
  AuthenticatedDashboardEyeStrainRoute: typeof AuthenticatedDashboardEyeStrainRoute
  AuthenticatedDashboardGlucoseRoute: typeof AuthenticatedDashboardGlucoseRoute
  AuthenticatedDashboardHearingRoute: typeof AuthenticatedDashboardHearingRoute
  AuthenticatedDashboardOxygenRoute: typeof AuthenticatedDashboardOxygenRoute
  AuthenticatedDashboardStressRoute: typeof AuthenticatedDashboardStressRoute
  AuthenticatedDashboardTemperatureRoute: typeof AuthenticatedDashboardTemperatureRoute
  AuthenticatedDashboardUvRoute: typeof AuthenticatedDashboardUvRoute
  AuthenticatedDashboardWeightRoute: typeof AuthenticatedDashboardWeightRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBioAgeRoute: AuthenticatedDashboardBioAgeRoute,
    AuthenticatedDashboardBoneHealthRoute:
      AuthenticatedDashboardBoneHealthRoute,
    AuthenticatedDashboardDevicesRoute: AuthenticatedDashboardDevicesRoute,
    AuthenticatedDashboardEnergyRoute: AuthenticatedDashboardEnergyRoute,
    AuthenticatedDashboardEyeStrainRoute: AuthenticatedDashboardEyeStrainRoute,
    AuthenticatedDashboardGlucoseRoute: AuthenticatedDashboardGlucoseRoute,
    AuthenticatedDashboardHearingRoute: AuthenticatedDashboardHearingRoute,
    AuthenticatedDashboardOxygenRoute: AuthenticatedDashboardOxygenRoute,
    AuthenticatedDashboardStressRoute: AuthenticatedDashboardStressRoute,
    AuthenticatedDashboardTemperatureRoute:
      AuthenticatedDashboardTemperatureRoute,
    AuthenticatedDashboardUvRoute: AuthenticatedDashboardUvRoute,
    AuthenticatedDashboardWeightRoute: AuthenticatedDashboardWeightRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBreatheRoute: typeof AuthenticatedBreatheRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedDietPlanRoute: typeof AuthenticatedDietPlanRoute
  AuthenticatedExerciseTrackerRoute: typeof AuthenticatedExerciseTrackerRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedHeartRhythmRoute: typeof AuthenticatedHeartRhythmRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedSenseCheckRoute: typeof AuthenticatedSenseCheckRoute
  AuthenticatedSleepTrackerRoute: typeof AuthenticatedSleepTrackerRoute
  AuthenticatedWaterTrackerRoute: typeof AuthenticatedWaterTrackerRoute
  AuthenticatedToolsToolRoute: typeof AuthenticatedToolsToolRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBreatheRoute: AuthenticatedBreatheRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedDietPlanRoute: AuthenticatedDietPlanRoute,
  AuthenticatedExerciseTrackerRoute: AuthenticatedExerciseTrackerRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedHeartRhythmRoute: AuthenticatedHeartRhythmRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedSenseCheckRoute: AuthenticatedSenseCheckRoute,
  AuthenticatedSleepTrackerRoute: AuthenticatedSleepTrackerRoute,
  AuthenticatedWaterTrackerRoute: AuthenticatedWaterTrackerRoute,
  AuthenticatedToolsToolRoute: AuthenticatedToolsToolRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  SosRoute: SosRoute,
  TermsRoute: TermsRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
