/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SosRouteImport } from './routes/sos'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWaterTrackerRouteImport } from './routes/_authenticated/water-tracker'
import { Route as AuthenticatedSleepTrackerRouteImport } from './routes/_authenticated/sleep-tracker'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedHeartRhythmRouteImport } from './routes/_authenticated/heart-rhythm'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedExerciseTrackerRouteImport } from './routes/_authenticated/exercise-tracker'
import { Route as AuthenticatedDietPlanRouteImport } from './routes/_authenticated/diet-plan'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBreatheRouteImport } from './routes/_authenticated/breathe'
import { Route as AuthenticatedToolsToolRouteImport } from './routes/_authenticated/tools/$tool'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWaterTrackerRoute =
  AuthenticatedWaterTrackerRouteImport.update({
    id: '/water-tracker',
    path: '/water-tracker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSleepTrackerRoute =
  AuthenticatedSleepTrackerRouteImport.update({
    id: '/sleep-tracker',
    path: '/sleep-tracker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHeartRhythmRoute =
  AuthenticatedHeartRhythmRouteImport.update({
    id: '/heart-rhythm',
    path: '/heart-rhythm',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExerciseTrackerRoute =
  AuthenticatedExerciseTrackerRouteImport.update({
    id: '/exercise-tracker',
    path: '/exercise-tracker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDietPlanRoute = AuthenticatedDietPlanRouteImport.update({
  id: '/diet-plan',
  path: '/diet-plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBreatheRoute = AuthenticatedBreatheRouteImport.update({
  id: '/breathe',
  path: '/breathe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsToolRoute = AuthenticatedToolsToolRouteImport.update({
  id: '/tools/$tool',
  path: '/tools/$tool',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/breathe': typeof AuthenticatedBreatheRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diet-plan': typeof AuthenticatedDietPlanRoute
  '/exercise-tracker': typeof AuthenticatedExerciseTrackerRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/heart-rhythm': typeof AuthenticatedHeartRhythmRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/sleep-tracker': typeof AuthenticatedSleepTrackerRoute
  '/water-tracker': typeof AuthenticatedWaterTrackerRoute
  '/tools/$tool': typeof AuthenticatedToolsToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/breathe': typeof AuthenticatedBreatheRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diet-plan': typeof AuthenticatedDietPlanRoute
  '/exercise-tracker': typeof AuthenticatedExerciseTrackerRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/heart-rhythm': typeof AuthenticatedHeartRhythmRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/sleep-tracker': typeof AuthenticatedSleepTrackerRoute
  '/water-tracker': typeof AuthenticatedWaterTrackerRoute
  '/tools/$tool': typeof AuthenticatedToolsToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/_authenticated/breathe': typeof AuthenticatedBreatheRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diet-plan': typeof AuthenticatedDietPlanRoute
  '/_authenticated/exercise-tracker': typeof AuthenticatedExerciseTrackerRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/heart-rhythm': typeof AuthenticatedHeartRhythmRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/sleep-tracker': typeof AuthenticatedSleepTrackerRoute
  '/_authenticated/water-tracker': typeof AuthenticatedWaterTrackerRoute
  '/_authenticated/tools/$tool': typeof AuthenticatedToolsToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cookies'
    | '/privacy'
    | '/sos'
    | '/terms'
    | '/breathe'
    | '/dashboard'
    | '/diet-plan'
    | '/exercise-tracker'
    | '/goals'
    | '/heart-rhythm'
    | '/history'
    | '/sleep-tracker'
    | '/water-tracker'
    | '/tools/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cookies'
    | '/privacy'
    | '/sos'
    | '/terms'
    | '/breathe'
    | '/dashboard'
    | '/diet-plan'
    | '/exercise-tracker'
    | '/goals'
    | '/heart-rhythm'
    | '/history'
    | '/sleep-tracker'
    | '/water-tracker'
    | '/tools/$tool'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cookies'
    | '/privacy'
    | '/sos'
    | '/terms'
    | '/_authenticated/breathe'
    | '/_authenticated/dashboard'
    | '/_authenticated/diet-plan'
    | '/_authenticated/exercise-tracker'
    | '/_authenticated/goals'
    | '/_authenticated/heart-rhythm'
    | '/_authenticated/history'
    | '/_authenticated/sleep-tracker'
    | '/_authenticated/water-tracker'
    | '/_authenticated/tools/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  SosRoute: typeof SosRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/water-tracker': {
      id: '/_authenticated/water-tracker'
      path: '/water-tracker'
      fullPath: '/water-tracker'
      preLoaderRoute: typeof AuthenticatedWaterTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sleep-tracker': {
      id: '/_authenticated/sleep-tracker'
      path: '/sleep-tracker'
      fullPath: '/sleep-tracker'
      preLoaderRoute: typeof AuthenticatedSleepTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/heart-rhythm': {
      id: '/_authenticated/heart-rhythm'
      path: '/heart-rhythm'
      fullPath: '/heart-rhythm'
      preLoaderRoute: typeof AuthenticatedHeartRhythmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exercise-tracker': {
      id: '/_authenticated/exercise-tracker'
      path: '/exercise-tracker'
      fullPath: '/exercise-tracker'
      preLoaderRoute: typeof AuthenticatedExerciseTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diet-plan': {
      id: '/_authenticated/diet-plan'
      path: '/diet-plan'
      fullPath: '/diet-plan'
      preLoaderRoute: typeof AuthenticatedDietPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/breathe': {
      id: '/_authenticated/breathe'
      path: '/breathe'
      fullPath: '/breathe'
      preLoaderRoute: typeof AuthenticatedBreatheRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/$tool': {
      id: '/_authenticated/tools/$tool'
      path: '/tools/$tool'
      fullPath: '/tools/$tool'
      preLoaderRoute: typeof AuthenticatedToolsToolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBreatheRoute: typeof AuthenticatedBreatheRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDietPlanRoute: typeof AuthenticatedDietPlanRoute
  AuthenticatedExerciseTrackerRoute: typeof AuthenticatedExerciseTrackerRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedHeartRhythmRoute: typeof AuthenticatedHeartRhythmRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedSleepTrackerRoute: typeof AuthenticatedSleepTrackerRoute
  AuthenticatedWaterTrackerRoute: typeof AuthenticatedWaterTrackerRoute
  AuthenticatedToolsToolRoute: typeof AuthenticatedToolsToolRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBreatheRoute: AuthenticatedBreatheRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDietPlanRoute: AuthenticatedDietPlanRoute,
  AuthenticatedExerciseTrackerRoute: AuthenticatedExerciseTrackerRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedHeartRhythmRoute: AuthenticatedHeartRhythmRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedSleepTrackerRoute: AuthenticatedSleepTrackerRoute,
  AuthenticatedWaterTrackerRoute: AuthenticatedWaterTrackerRoute,
  AuthenticatedToolsToolRoute: AuthenticatedToolsToolRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  SosRoute: SosRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
